version: "3.8"
services:
  coturn:
    image: instrumentisto/coturn:4.6.2
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
    command: ["-c", "/etc/turnserver.conf"]